// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV5iCt89wTngjUz2l3cjL1fVrHtN56198',
    appId: '1:1063390943216:web:08c0932c9d01b328916f35',
    messagingSenderId: '1063390943216',
    projectId: 'doctor-appointment-74823',
    authDomain: 'doctor-appointment-74823.firebaseapp.com',
    storageBucket: 'doctor-appointment-74823.firebasestorage.app',
    measurementId: 'G-8Q9M0YR0G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt5_E9AYGmVYIYLAavgErfeQFcUCzvn2I',
    appId: '1:1063390943216:android:9a50cc4579d38957916f35',
    messagingSenderId: '1063390943216',
    projectId: 'doctor-appointment-74823',
    storageBucket: 'doctor-appointment-74823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0cOgVdXPbabnqnX2owMG4O2hJnKcdmao',
    appId: '1:1063390943216:ios:0a9a4a62e1ed52f5916f35',
    messagingSenderId: '1063390943216',
    projectId: 'doctor-appointment-74823',
    storageBucket: 'doctor-appointment-74823.firebasestorage.app',
    iosBundleId: 'com.example.healthinfoFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0cOgVdXPbabnqnX2owMG4O2hJnKcdmao',
    appId: '1:1063390943216:ios:0a9a4a62e1ed52f5916f35',
    messagingSenderId: '1063390943216',
    projectId: 'doctor-appointment-74823',
    storageBucket: 'doctor-appointment-74823.firebasestorage.app',
    iosBundleId: 'com.example.healthinfoFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV5iCt89wTngjUz2l3cjL1fVrHtN56198',
    appId: '1:1063390943216:web:8e77acd3ce03b23a916f35',
    messagingSenderId: '1063390943216',
    projectId: 'doctor-appointment-74823',
    authDomain: 'doctor-appointment-74823.firebaseapp.com',
    storageBucket: 'doctor-appointment-74823.firebasestorage.app',
    measurementId: 'G-QC2FFG5KE9',
  );
}
